os: osx
osx_image: xcode10.2
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=AlamofireNetworkActivityIndicator.xcodeproj
  - SCHEME="AlamofireNetworkActivityIndicator"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone X"    POD_LINT="YES"
    - DESTINATION="OS=11.4,name=iPhone 8"    POD_LINT="NO"
    - DESTINATION="OS=10.3.1,name=iPhone 7"  POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6"     POD_LINT="NO"
script:
  - set -o pipefail
  - git submodule update --init --recursive
  - pod repo update
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;

  # Build Framework in Release and Run Tests  
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
